[tool.poetry]
name = "idk"
version = "0.1.0"
description = ""
authors = ["Emangod"]

[tool.poetry.dependencies]
python = "^3.8"
scapy = "^2.4.4"
figlet = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
